config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :restaurants do
    resources :reviews, only: %i[new create]
  end
  resources :reviews, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORIES = %w[chinese italian japanese french belgian]

  has_many :reviews, dependent: :destroy

  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: CATEGORIES }
end

app/models/review.rb
class Review < ApplicationRecord
  RATINGS = [0, 1, 2, 3, 4, 5]
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true }, inclusion: { in: RATINGS }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show edit update destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit

  end

  def update

  end

  def destroy
    @restaurant.delete

    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end


  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant

    if @review.save
      redirect_to @restaurant
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    redirect_to @review.restaurant
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
    <%= f.input :name %>
    <%= f.input :category, collection: Restaurant::CATEGORIES %>
    <%= f.input :address %>
    <%= f.input :phone_number %>

    <%= f.submit %>
  <% end %>

app/views/restaurants/index.html.erb
<div class="container">
<h1>All Restaurants</h1>
<ul>
  <% @restaurants.each do |restaurant| %>
  <li><%= link_to restaurant.name, restaurant %></li>
  <% end %>
</ul>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <h1>Add New Restaurant</h1>
  <%= render 'form' %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <h1><%= @restaurant.name %></h1>
  <strong>Address: </strong> <%= @restaurant.address %><br>
  <strong>Category: </strong> <%= @restaurant.category.capitalize %><br>
  <strong>Phone Number: </strong><%= @restaurant.phone_number %>

  <hr>

  <h2>Comments (<%= @restaurant.reviews.length %>)</h2>
    <%= render 'reviews/form' %>
    <% @restaurant.reviews.each do |review| %>
    <div> <%= review.content %> - <strong><%= review.rating %></strong> (<%= review.created_at %>) - <%= link_to 'delete', review_path(review), data: {
      turbo_method: 'delete',
      turbo_confirm: 'Are you sure?'
    } %> </div>
  <% end %>

  <hr>

  <%= link_to "Back to Main Page", restaurants_path %>
  <%= link_to "Delete Restaurant", restaurant_path(@restaurant), data: {
    turbo_method: 'delete',
    turbo_confirm: 'Are you sure?' } %>

</div>

app/views/reviews/_form.html.erb
<%= simple_form_for([@restaurant, @review]) do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, collection: Review::RATINGS %>
  <%= f.submit %>
<% end %>

app/views/reviews/new.html.erb
<div class="container">
  <h1>Add New Review for <%= @restaurant.name %></h1>
  <%= render 'reviews/form' %>
</div>